# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto_msg.proto\"\x84\x01\n\x07\x43ommand\x12\r\n\x05valve\x18\x01 \x01(\x05\x12\x10\n\x08\x64iverter\x18\x02 \x01(\x08\x12\x0f\n\x07n_steps\x18\x03 \x01(\r\x12\x0f\n\x07t_steps\x18\x04 \x01(\r\x12\x11\n\tstart_btn\x18\x05 \x01(\x08\x12\x11\n\treset_btn\x18\x06 \x01(\x08\x12\x10\n\x08next_btn\x18\x07 \x01(\x08\"Y\n\x05Reply\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x0e\n\x06weight\x18\x02 \x01(\x02\x12\x15\n\rtime_interval\x18\x03 \x01(\x02\x12\x14\n\x0c\x63urrent_step\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMAND._serialized_start=20
  _COMMAND._serialized_end=152
  _REPLY._serialized_start=154
  _REPLY._serialized_end=243
# @@protoc_insertion_point(module_scope)
